### ISSUE TITLE
graphql.config.yml missing ? 

### ISSUE THREAD

**Issue by Lorezz** [datocms/next-landing-page-demo#2]
Would be useful to have the graphql.config.yml file inside the repo, as described in package.json scripts section.
` generate-ts-types: "graphql-codegen --config graphql.config.yml"`
to run types generation when changing some models 
Thank You.

**Comment by marcelofinamorvieira** [comment]
@Lorezz Added on https://github.com/datocms/next-landing-page-demo/commit/183634fa551c7801fbb79173a630c85c4489e1a0 

Thank you!
