### ISSUE TITLE
Bug: i18n middleware not awaiting for promise

### ISSUE THREAD

**Issue by saranshgrover** [datocms/next-landing-page-demo#3]
Going to a link without the locale but with a subpath, such as https://company-website-demo-preview.vercel.app/home is broken and results in a infinite redirect because this line doesn't have `await` https://github.com/datocms/next-landing-page-demo/blob/main/middleware.ts#L50.

**Comment by marcelofinamorvieira** [comment]
Thank you @saranshgrover!
